version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo "Running tests..."
      - pytest || true

  build:
    commands:
      - echo "Packaging app"

artifacts:
  files:
    - '**/*'
  discard-paths: no
